In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
url = "https://www.forbes.com/billionaires/page-data/index/page-data.json"

response = requests.get(url)

json_data = response.json()

In [3]:
rows = json_data['result']['pageContext']['tableData']

In [4]:
tableData = {
    k: v
    for (k, v) in rows[0].items()
    if
    (k != 'person') & # dict
    (k != 'employment') & # dict
    (k != 'qas') & # two dicts
    (k != 'bios') & # list
    (k != 'abouts') & #list
    (k != 'csfDisplayFields') #list
}
tableData

{'name': 'Billionaires',
 'year': 2022,
 'month': 4,
 'uri': 'elon-musk',
 'rank': 1,
 'listUri': 'billionaires',
 'finalWorth': 219000,
 'category': 'Automotive',
 'otherCompensation': 0,
 'visible': True,
 'personName': 'Elon Musk',
 'age': 50,
 'country': 'United States',
 'state': 'Texas',
 'city': 'Austin',
 'source': 'Tesla, SpaceX',
 'industries': 'Automotive',
 'countryOfCitizenship': 'United States',
 'organization': 'Tesla',
 'timestamp': 1664284092360,
 'version': 1,
 'naturalId': 'faris/5/2022/14117',
 'position': 1,
 'imageExists': True,
 'selfMade': True,
 'status': 'U',
 'gender': 'M',
 'birthDate': 46915200000,
 'lastName': 'Musk',
 'firstName': 'Elon',
 'listDescription': "The World's Billionaires",
 'title': 'CEO',
 'date': 1649134860000,
 'wealthList': False,
 'familyList': False,
 'selfMadeRank': 8,
 'thumbnail': 'http://specials-images.forbesimg.com/imageserve/62d700cd6094d2c180f269b9/280x425.jpg?fit=scale&background=000000',
 'residenceStateRegion': 'South',
 'squareImage': 'https://specials-images.forbesimg.com/imageserve/62d700cd6094d2c180f269b9/416x416.jpg?background=000000&cropX1=0&cropX2=959&cropY1=0&cropY2=959',
 'bioSuppress': False,
 'suppressOnProfiles': False,
 'premiumProfile': False,
 'philanthropyScore': 1,
 'embargo': False,
 'netWorth': '$219 B'}

In [5]:
person = {
    list(rows[0].keys())[9]+'_'+k:v
    for (k,v) in rows[0][list(rows[0].keys())[9]].items()
}
person

{'person_name': 'Elon Musk',
 'person_uri': 'elon-musk',
 'person_imageExists': True,
 'person_squareImage': 'https://specials-images.forbesimg.com/imageserve/62d700cd6094d2c180f269b9/416x416.jpg?background=000000&cropX1=0&cropX2=959&cropY1=0&cropY2=959'}

In [6]:
employment = {
    list(rows[0].keys())[33]+'_'+k:v
    for (k,v) in rows[0][list(rows[0].keys())[33]].items()
}
employment

{'employment_name': 'Tesla',
 'employment_uri': 'companies/tesla',
 'employment_title': 'CEO',
 'employment_government': False}

In [7]:
rows[0]['qas']

[{'question': 'Innovative Leaders: 12-month Sales Growth, %',
  'answer': '27.03',
  'hidden': False},
 {'question': 'Innovative Leaders: Company Innovation Premium',
  'answer': '72.16',
  'hidden': False}]

In [8]:
pd.DataFrame([tableData])

,name,year,month,uri,rank,listUri,finalWorth,category,otherCompensation,visible,...,selfMadeRank,thumbnail,residenceStateRegion,squareImage,bioSuppress,suppressOnProfiles,premiumProfile,philanthropyScore,embargo,netWorth
0,Billionaires,2022,4,elon-musk,1,billionaires,219000,Automotive,0,True,...,8,http://specials-images.forbesimg.com/imageserv...,South,https://specials-images.forbesimg.com/imageser...,False,False,False,1,False,$219 B

In [9]:
ls_=[]

for row in rows:
    tableData = {
        k: v
        for (k, v) in row.items()
        if
        (k != 'person') & # dict
        (k != 'employment') & # dict
        (k != 'qas') & # two dicts
        (k != 'bios') & # list
        (k != 'abouts') & #list
        (k != 'csfDisplayFields') #list
        }
    ls_.append(tableData)

In [10]:
data = pd.DataFrame(ls_)

In [11]:
cols_to_drop = [
    'parentListUri',
    'organization',
    'title',
    'selfMadeRank',
    'residenceStateRegion',
    'embargo',
    'residenceMsa',
    'impactInvestor',
    'numberOfSiblings',
    'numberOfSiblingsEst',
    'bio',
    'totalCharitableDonation',
    'charitableDonationPercentage',
    'thumbnail',
    'notableDeal',
    'valueCreated',
    'primaryIndustry',
    'portraitImage',
    'landscapeImage',
    'clients']

data.drop(cols_to_drop, axis=1, inplace=True)

KeyError: "['totalCharitableDonation', 'charitableDonationPercentage'] not found in axis"

In [12]:
data.isna().sum()

name                       0
year                       0
month                      0
uri                        0
rank                       0
listUri                    0
finalWorth                 0
category                   0
otherCompensation          0
visible                    0
personName                 0
age                        0
country                   13
state                   1920
city                      44
source                     0
industries                 0
countryOfCitizenship       0
organization            2321
timestamp                  0
version                    0
naturalId                  0
position                   0
imageExists                0
selfMade                   0
status                     0
gender                    16
birthDate                 98
lastName                   0
firstName                  6
listDescription            0
title                   2278
date                       0
wealthList                 0
familyList                 0
selfMadeRank            2102
thumbnail               2464
residenceStateRegion    1928
squareImage              679
bioSuppress                0
suppressOnProfiles         0
premiumProfile             0
philanthropyScore          0
embargo                 2088
netWorth                   0
parentListUri            580
residenceMsa            2043
impactInvestor          2629
numberOfSiblings        2541
numberOfSiblingsEst     2541
bio                     2603
notableDeal             2654
valueCreated            2648
primaryIndustry         2667
portraitImage           2659
landscapeImage          2659
clients                 2667
dtype: int64

In [15]:
data

,name,year,month,uri,rank,listUri,finalWorth,category,otherCompensation,visible,personName,age,country,state,city,source,industries,countryOfCitizenship,organization,timestamp,version,naturalId,position,imageExists,selfMade,status,gender,birthDate,lastName,firstName,listDescription,title,date,wealthList,familyList,selfMadeRank,thumbnail,residenceStateRegion,squareImage,bioSuppress,suppressOnProfiles,premiumProfile,philanthropyScore,embargo,netWorth,parentListUri,residenceMsa,impactInvestor,numberOfSiblings,numberOfSiblingsEst,bio,notableDeal,valueCreated,primaryIndustry,portraitImage,landscapeImage,clients
0,Billionaires,2022,4,elon-musk,1,billionaires,219000,Automotive,0,True,Elon Musk,50,United States,Texas,Austin,"Tesla, SpaceX",Automotive,United States,Tesla,1664284092360,1,faris/5/2022/14117,1,True,True,U,M,4.691520e+10,Musk,Elon,The World's Billionaires,CEO,1649134860000,False,False,8.0,http://specials-images.forbesimg.com/imageserv...,South,https://specials-images.forbesimg.com/imageser...,False,False,False,1,False,$219 B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Billionaires,2022,4,jeff-bezos,2,billionaires,171000,Technology,0,True,Jeff Bezos,58,United States,Washington,Seattle,Amazon,Technology,United States,Amazon,1664284094526,1,faris/5/2022/6713,2,True,True,D,M,-1.884384e+11,Bezos,Jeff,The World's Billionaires,Chairman and Founder,1649134860000,False,False,8.0,NaN,West,https://specials-images.forbesimg.com/imageser...,False,False,False,1,False,$171 B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Billionaires,2022,4,bernard-arnault,3,billionaires,158000,Fashion & Retail,0,True,Bernard Arnault & family,73,France,NaN,Paris,LVMH,Fashion & Retail,France,LVMH MoÃ«t Hennessy Louis Vuitton,1649136422879,1,faris/5/2022/4800,3,True,False,U,M,-6.572448e+11,Arnault,Bernard,The World's Billionaires,Chairman and CEO,1649116800000,False,False,NaN,NaN,NaN,//specials-images.forbesimg.com/imageserve/5dc...,False,False,False,N/A,NaN,$158 B,billionaires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Billionaires,2022,4,bill-gates,4,billionaires,129000,Technology,0,True,Bill Gates,66,United States,Washington,Medina,Microsoft,Technology,United States,Bill & Melinda Gates Foundation,1664284096498,1,faris/5/2022/5772,4,True,True,U,M,-4.474656e+11,Gates,Bill,The World's Billionaires,Cofounder,1649134860000,False,False,8.0,http://specials-images.forbesimg.com/imageserv...,West,https://specials-images.forbesimg.com/imageser...,False,False,False,4,False,$129 B,NaN,"Seattle-Tacoma-Bellevue, WA",True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Billionaires,2022,4,warren-buffett,5,billionaires,118000,Finance & Investments,0,True,Warren Buffett,91,United States,Nebraska,Omaha,Berkshire Hathaway,Finance & Investments,United States,Berkshire Hathaway Inc. (Cl A),1664284100407,1,faris/5/2022/5381,5,True,True,U,M,-1.241482e+12,Buffett,Warren,The World's Billionaires,CEO,1649134860000,False,False,8.0,NaN,Midwest,//specials-images.forbesimg.com/imageserve/5ba...,False,False,False,5,False,$118 B,NaN,"Omaha, NE",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2663,Billionaires,2022,4,zhang-yuqiang,2578,billionaires,1000,Manufacturing,0,True,Zhang Yuqiang,66,China,NaN,Tongxiang,Fiberglass,Manufacturing,China,NaN,1649106322824,1,faris/5/2022/736,2664,False,True,E,M,-4.523904e+11,Zhang,Yuqiang,The World's Billionaires,NaN,1649116800000,False,False,NaN,NaN,NaN,NaN,False,False,False,N/A,NaN,$1 B,billionaires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2664,Billionaires,2022,4,zhou-ruxin,2578,billionaires,1000,Technology,0,True,Zhou Ruxin,59,China,NaN,Beijing,Navigation,Technology,China,NaN,1649106324192,1,faris/5/2022/784,2665,False,True,D,M,-2.158272e+11,Zhou,Ruxin,The World's Billionaires,NaN,1649116800000,False,False,NaN,NaN,NaN,NaN,False,False,False,N/A,NaN,$1 B,billionaires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2665,Billionaires,2022,4,wen-zhou,2578,billionaires,1000,Manufacturing,0,True,Wen Zhou & family,57,China,NaN,Shanghai,chemicals,Manufacturing,China,NaN,1649106325939,1,faris/5/2022/12437,2666,False,True,D,M,-1.522368e+11,Zhou,Wen,The World's Billionaires,NaN,1649116800000,False,False,NaN,NaN,NaN,NaN,False,False,False,N/A,NaN,$1 B,billionaires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2666,Billionaires,2022,4,zhou-yifeng,2578,billionaires,1000,Energy,0,True,Zhou Yifeng & family,43,China,NaN,Zhangjiagang,liquefied petroleum gas,Energy,China,NaN,1649106327425,1,faris/5/2022/1275,2667,False,True,D,F,2.689632e+11,Zhou,Yifeng,The World's Billionaires,NaN,1649116800000,False,False,NaN,NaN,NaN,NaN,False,False,False,N/A,NaN,$1 B,billionaires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2667,Billionaires,2022,4,zhuang-kuilong,2578,billionaires,1000,Manufacturing,0,True,Zhuang Kuilong & family,59,China,NaN,Jiaxing,polyester,Manufacturing,China,NaN,1649106328778,1,faris/5/2022/203531,2668,False,True,D,M,-2.382048e+11,Zhuang,Kuilong,The World's Billionaires,NaN,1649116800000,False,False,NaN,NaN,NaN,NaN,False,False,False,N/A,NaN,$1 B,billionaires,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN