In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
url = "https://www.forbes.com/billionaires/page-data/index/page-data.json"

response = requests.get(url)

json_data = response.json()

In [3]:
rows = json_data['result']['pageContext']['tableData']

In [4]:
tableData = {
    k: v
    for (k, v) in rows[0].items()
    if
    (k != 'person') & # dict
    (k != 'employment') & # dict
    (k != 'qas') & # two dicts
    (k != 'bios') & # list
    (k != 'abouts') & #list
    (k != 'csfDisplayFields') #list
}

In [ ]:
person = {
    list(rows[0].keys())[9]+'_'+k:v
    for (k,v) in rows[0][list(rows[0].keys())[9]].items()
}
person

In [ ]:
employment = {
    list(rows[0].keys())[33]+'_'+k:v
    for (k,v) in rows[0][list(rows[0].keys())[33]].items()
}
employment

In [ ]:
rows[0]['qas']

In [5]:
pd.DataFrame([tableData])

,name,year,month,uri,rank,listUri,finalWorth,category,otherCompensation,visible,...,selfMadeRank,thumbnail,residenceStateRegion,squareImage,bioSuppress,suppressOnProfiles,premiumProfile,philanthropyScore,embargo,netWorth
0,Billionaires,2022,4,elon-musk,1,billionaires,219000,Automotive,0,True,...,8,http://specials-images.forbesimg.com/imageserv...,South,https://specials-images.forbesimg.com/imageser...,False,False,False,1,False,$219 B

In [6]:
ls_=[]

for row in rows:
    tableData = {
        k: v
        for (k, v) in row.items()
        if
        (k != 'person') & # dict
        (k != 'employment') & # dict
        (k != 'qas') & # two dicts
        (k != 'bios') & # list
        (k != 'abouts') & #list
        (k != 'csfDisplayFields') #list
        }
    ls_.append(tableData)

In [33]:
data = pd.DataFrame(ls_)

In [34]:
cols_to_drop = [
    'parentListUri',
    'organization',
    'title',
    'selfMadeRank',
    'residenceStateRegion',
    'embargo',
    'residenceMsa',
    'impactInvestor',
    'numberOfSiblings',
    'numberOfSiblingsEst',
    'bio',
    # 'totalCharitableDonation',
    # 'charitableDonationPercentage',
    'thumbnail',
    'notableDeal',
    'valueCreated',
    'primaryIndustry',
    'portraitImage',
    'landscapeImage',
    'clients']

data.drop(cols_to_drop, axis=1, inplace=True)

In [35]:
data['squareImage'].fillna('https://i.forbesimg.com/media/assets/forbes_1200x1200.jpg', inplace=True)

data['country'].fillna('Not Specified', inplace=True)

data['state'].fillna('Not Specified', inplace=True)

data['city'].fillna('Not Specified', inplace=True)

data['gender'].fillna('Not Specified', inplace=True)

data['birthDate'].fillna('Not Specified', inplace=True)

data['firstName'].fillna('Not Specified', inplace=True)

In [36]:
data.isna().sum()

name                    0
year                    0
month                   0
uri                     0
rank                    0
listUri                 0
finalWorth              0
category                0
otherCompensation       0
visible                 0
personName              0
age                     0
country                 0
state                   0
city                    0
source                  0
industries              0
countryOfCitizenship    0
timestamp               0
version                 0
naturalId               0
position                0
imageExists             0
selfMade                0
status                  0
gender                  0
birthDate               0
lastName                0
firstName               0
listDescription         0
date                    0
wealthList              0
familyList              0
squareImage             0
bioSuppress             0
suppressOnProfiles      0
premiumProfile          0
philanthropyScore       0
netWorth                0
dtype: int64

In [24]:
pd.options.display.max_columns = None

In [27]:
data[data['gender'].isna()]

,name,year,month,uri,rank,listUri,finalWorth,category,otherCompensation,visible,personName,age,country,state,city,source,industries,countryOfCitizenship,timestamp,version,naturalId,position,imageExists,selfMade,status,gender,birthDate,lastName,firstName,listDescription,date,wealthList,familyList,squareImage,bioSuppress,suppressOnProfiles,premiumProfile,philanthropyScore,netWorth
34,Billionaires,2022,4,beate-heister-karl-albrecht-jr,35,billionaires,36800,Fashion & Retail,0,True,Beate Heister & Karl Albrecht Jr. & family,0,Germany,NaN,NaN,supermarkets,Fashion & Retail,Germany,1649102209355,1,faris/5/2022/196408,35,False,False,D,NaN,NaN,Albrecht Jr.,Beate Heister & Karl,The World's Billionaires,1649116800000,False,False,https://specials-images.forbesimg.com/imageser...,False,False,False,N/A,$36.8 B
101,Billionaires,2022,4,gianluigi-rafaela-aponte,102,billionaires,16800,Logistics,0,True,Gianluigi & Rafaela Aponte,81,Switzerland,NaN,Geneva,Shipping,Logistics,Switzerland,1649102314266,1,faris/5/2022/7642,102,True,True,U,NaN,-9.313920e+11,Aponte,Gianluigi & Rafaela,The World's Billionaires,1649116800000,False,False,//specials-images.forbesimg.com/imageserve/5e7...,False,False,False,N/A,$16.8 B
212,Billionaires,2022,4,tom-judy-love,213,billionaires,9700,Fashion & Retail,0,True,Tom & Judy Love,0,United States,Oklahoma,Oklahoma City,retail & gas stations,Fashion & Retail,United States,1649102493159,1,faris/5/2022/193187,213,True,True,D,NaN,NaN,Love,Tom & Judy,The World's Billionaires,1649116800000,False,False,//specials-images.forbesimg.com/imageserve/59d...,False,False,False,1,$9.7 B
283,Billionaires,2022,4,stewart-lynda-resnick,284,billionaires,8000,Food & Beverage,0,True,Stewart & Lynda Resnick,0,United States,California,Beverly Hills,"agriculture, water",Food & Beverage,United States,1664288978473,1,faris/5/2022/5928,284,True,True,U,NaN,NaN,Resnick,Stewart & Lynda,The World's Billionaires,1649134860000,False,False,//specials-images.forbesimg.com/imageserve/5d8...,False,False,False,3,$8 B
303,Billionaires,2022,4,bajaj-siblings,304,billionaires,7700,Automotive,0,True,Bajaj siblings,0,India,NaN,Pune,"two-wheelers, finance",Automotive,India,1649322462203,1,faris/5/2022/247568,304,False,False,N,NaN,NaN,Bajaj,siblings,The World's Billionaires,1649116800000,False,False,https://i.forbesimg.com/media/assets/forbes_12...,False,False,False,N/A,$7.7 B
309,Billionaires,2022,4,safra,304,billionaires,7700,Finance & Investments,0,True,Safra siblings,0,Brazil,NaN,Sao Paulo,banking,Finance & Investments,Brazil,1649102643703,1,faris/5/2022/239987,310,False,False,U,NaN,NaN,Safra,NaN,The World's Billionaires,1649116800000,False,False,https://i.forbesimg.com/media/assets/forbes_12...,False,False,False,N/A,$7.7 B
368,Billionaires,2022,4,alejandro-bailleres-gual,369,billionaires,6700,Diversified,0,True,Alejandro Bailleres Gual & siblings,61,Mexico,NaN,NaN,mining,Diversified,Mexico,1649102735624,1,faris/5/2022/247551,369,False,False,N,NaN,-2.839968e+11,Bailleres Gual,Alejandro,The World's Billionaires,1649116800000,False,False,https://specials-images.forbesimg.com/imageser...,False,False,False,N/A,$6.7 B
782,Billionaires,2022,4,vinod-anil-rai-gupta,778,billionaires,3800,Manufacturing,0,True,Vinod & Anil Rai Gupta,0,India,NaN,Delhi,electrical equipment,Manufacturing,India,1649103396039,1,faris/5/2022/196113,783,True,False,D,NaN,NaN,Gupta,Vinod & Anil Rai,The World's Billionaires,1649116800000,False,False,https://specials-images.forbesimg.com/imageser...,False,False,False,N/A,$3.8 B
822,Billionaires,2022,4,byju-raveendran-and-divya-gokulnath,822,billionaires,3600,Technology,0,True,Byju Raveendran and Divya Gokulnath,40,India,NaN,Bangalore,education technology,Technology,India,1649103462834,1,faris/5/2022/224464,823,False,True,U,NaN,3.632256e+11,Byju Raveendran,and Divya Gokulnath,The World's Billionaires,1649116800000,False,False,https://i.forbesimg.com/media/assets/forbes_12...,False,False,False,N/A,$3.6 B
953,Billionaires,2022,4,andrew-peggy-cherng,951,billionaires,3200,Food & Beverage,0,True,Andrew & Peggy Cherng,0,United States,Nevada,Las Vegas,restaurants,Food & Beverage,United States,1649103667465,1,faris/5/2022/13135,954,True,True,U,NaN,NaN,Cherng,Andrew & Peggy,The World's Billionaires,1649116800000,False,False,//specials-images.forbesimg.com/imageserve/57d...,False,False,False,N/A,$3.2 B
1049,Billionaires,2022,4,zhang-xin-pan-shiyi,1012,billionaires,3000,Real Estate,0,True,Zhang Xin & Pan Shiyi,56,China,NaN,Beijing,real estate,Real Estate,China,1649103821247,1,faris/5/2022/350,1050,False,True,D,NaN,-1.374624e+11,Zhang Xin & Pan,Shiyi,The World's Billionaires,1649116800000,False,False,//specials-images.forbesimg.com/imageserve/5e7...,False,False,False,N/A,$3 B
1245,Billionaires,2022,4,chuchat-petaumpai-daonapa-petampai,1238,billionaires,2500,Finance & Investments,0,True,Chuchat Petaumpai & Daonapa Petampai,69,Thailand,NaN,Bangkok,motorcycle loans,Finance & Investments,Thailand,1657031706371,1,faris/5/2022/196551,1246,False,True,D,NaN,-5.364576e+11,Chuchat Petaumpai &,Daonapa Petampai,The World's Billionaires,1649134860000,False,False,https://specials-images.forbesimg.com/imageser...,False,False,False,N/A,$2.5 B
1250,Billionaires,2022,4,yoichi-keiko-erikawa,1238,billionaires,2500,Media & Entertainment,0,True,Yoichi & Keiko Erikawa,0,Japan,NaN,Yokohama,videogames,Media & Entertainment,Japan,1654027693254,1,faris/5/2022/199619,1251,False,True,D,NaN,NaN,Erikawa,Yoichi & Keiko,The World's Billionaires,1649199600000,False,False,//specials-images.forbesimg.com/imageserve/58d...,False,False,False,N/A,$2.5 B
1359,Billionaires,2022,4,philip-cristina-green,1341,billionaires,2300,Fashion & Retail,0,True,Philip & Cristina Green,70,United Kingdom,NaN,London,fashion retail,Fashion & Retail,United Kingdom,1649104309689,1,faris/5/2022/7369,1360,True,True,D,NaN,-5.616864e+11,Green,Philip & Cristina,The World's Billionaires,1649116800000,False,False,//specials-images.forbesimg.com/imageserve/5e7...,False,False,False,N/A,$2.3 B
1444,Billionaires,2022,4,bill-and-jean-adderley,1445,billionaires,2100,Fashion & Retail,0,True,Bill and Jean Adderley & family,0,United Kingdom,NaN,Leicester,home furnishings,Fashion & Retail,United Kingdom,1649104443244,1,faris/5/2022/194821,1445,False,True,D,NaN,NaN,Adderley,Bill and Jean,The World's Billionaires,1649116800000,False,False,https://i.forbesimg.com/media/assets/forbes_12...,False,False,False,N/A,$2.1 B
1680,Billionaires,2022,4,mark-robyn-jones,1645,billionaires,1800,Finance & Investments,0,True,Mark & Robyn Jones,0,United States,Texas,Fort Worth,insurance,Finance & Investments,United States,1649104805794,1,faris/5/2022/223845,1681,False,True,D,NaN,NaN,Jones,Mark & Robyn,The World's Billionaires,1649116800000,False,False,https://specials-images.forbesimg.com/imageser...,False,False,False,N/A,$1.8 B